name: cyclone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter

  firebase_ui_firestore: ^1.5.5

  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  get_storage: ^2.1.1
  dots_indicator: ^3.0.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.2.5
  google_ml_vision: ^0.0.8
  flutter_contacts: ^1.1.7+1
  google_fonts: ^5.1.0
  url_launcher: ^6.1.14
  phish_detector: ^0.0.2
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 19

flutter:
  uses-material-design: true

  assets:
    - assets/
